version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
